set_property PACKAGE_PIN C17 [get_ports CLK_MOUSE] 
     set_property IOSTANDARD LVCMOS33 [get_ports CLK_MOUSE]
     set_property PULLUP true [get_ports CLK_MOUSE]
set_property PACKAGE_PIN B17 [get_ports DATA_MOUSE] 
     set_property IOSTANDARD LVCMOS33 [get_ports DATA_MOUSE]
     set_property PULLUP true [get_ports DATA_MOUSE]
set_property PACKAGE_PIN W5 [get_ports CLK] 
          set_property IOSTANDARD LVCMOS33 [get_ports CLK]
          create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports CLK]
set_property PACKAGE_PIN U18 [get_ports RESET] 
     set_property IOSTANDARD LVCMOS33 [get_ports RESET]
     
     
set_property PACKAGE_PIN V13 [get_ports {MouseStatus[0]}] 
     set_property IOSTANDARD LVCMOS33 [get_ports {MouseStatus[0]}]
set_property PACKAGE_PIN V3 [get_ports {MouseStatus[1]}] 
      set_property IOSTANDARD LVCMOS33 [get_ports {MouseStatus[1]}]
      
set_property PACKAGE_PIN W3 [get_ports {MouseStatus[2]}]   
      set_property IOSTANDARD LVCMOS33 [get_ports {MouseStatus[2]}] 
      
set_property PACKAGE_PIN U3 [get_ports {MouseStatus[3]}] 
      set_property IOSTANDARD LVCMOS33 [get_ports {MouseStatus[3]}]  
set_property PACKAGE_PIN P3 [get_ports {MouseStatus[4]}] 
      set_property IOSTANDARD LVCMOS33 [get_ports {MouseStatus[4]}]
set_property PACKAGE_PIN N3 [get_ports {MouseStatus[5]}] 
      set_property IOSTANDARD LVCMOS33 [get_ports {MouseStatus[5]}] 
set_property PACKAGE_PIN P1 [get_ports {MouseStatus[6]}] 
      set_property IOSTANDARD LVCMOS33 [get_ports {MouseStatus[6]}]
set_property PACKAGE_PIN L1 [get_ports {MouseStatus[7]}] 
      set_property IOSTANDARD LVCMOS33 [get_ports {MouseStatus[7]}]              

            
set_property PACKAGE_PIN W7 [get_ports {HEX_OUT[0]}] 
            set_property IOSTANDARD LVCMOS33 [get_ports {HEX_OUT[0]}]
set_property PACKAGE_PIN W6 [get_ports {HEX_OUT[1]}] 
            set_property IOSTANDARD LVCMOS33 [get_ports {HEX_OUT[1]}]
set_property PACKAGE_PIN U8 [get_ports {HEX_OUT[2]}] 
            set_property IOSTANDARD LVCMOS33 [get_ports {HEX_OUT[2]}]
set_property PACKAGE_PIN V8 [get_ports {HEX_OUT[3]}] 
            set_property IOSTANDARD LVCMOS33 [get_ports {HEX_OUT[3]}]
set_property PACKAGE_PIN U5 [get_ports {HEX_OUT[4]}] 
            set_property IOSTANDARD LVCMOS33 [get_ports {HEX_OUT[4]}]
set_property PACKAGE_PIN V5 [get_ports {HEX_OUT[5]}] 
            set_property IOSTANDARD LVCMOS33 [get_ports {HEX_OUT[5]}]
set_property PACKAGE_PIN U7 [get_ports {HEX_OUT[6]}] 
            set_property IOSTANDARD LVCMOS33 [get_ports {HEX_OUT[6]}]
            
set_property PACKAGE_PIN U2 [get_ports {Select[0]}] 
            set_property IOSTANDARD LVCMOS33 [get_ports {Select[0]}]
set_property PACKAGE_PIN U4 [get_ports {Select[1]}] 
            set_property IOSTANDARD LVCMOS33 [get_ports {Select[1]}]
set_property PACKAGE_PIN V4 [get_ports {Select[2]}] 
            set_property IOSTANDARD LVCMOS33 [get_ports {Select[2]}]
set_property PACKAGE_PIN W4 [get_ports {Select[3]}] 
            set_property IOSTANDARD LVCMOS33 [get_ports {Select[3]}]


set_property PACKAGE_PIN G2 [get_ports IR_LED] 
            set_property IOSTANDARD LVCMOS33 [get_ports IR_LED]

set_property PACKAGE_PIN G19 [get_ports {VGA_COLOUR[0]}]				
            set_property IOSTANDARD LVCMOS33 [get_ports {VGA_COLOUR[0]}] 
                
set_property PACKAGE_PIN H19 [get_ports {VGA_COLOUR[1]}]                
            set_property IOSTANDARD LVCMOS33 [get_ports {VGA_COLOUR[1]}] 
                
set_property PACKAGE_PIN J19 [get_ports {VGA_COLOUR[2]}]                
            set_property IOSTANDARD LVCMOS33 [get_ports {VGA_COLOUR[2]}] 
            
set_property PACKAGE_PIN N18 [get_ports {VGA_COLOUR[3]}]                
            set_property IOSTANDARD LVCMOS33 [get_ports {VGA_COLOUR[3]}] 
                
set_property PACKAGE_PIN L18 [get_ports {VGA_COLOUR[4]}]                
            set_property IOSTANDARD LVCMOS33 [get_ports {VGA_COLOUR[4]}]
            
set_property PACKAGE_PIN J17 [get_ports {VGA_COLOUR[5]}]                
            set_property IOSTANDARD LVCMOS33 [get_ports {VGA_COLOUR[5]}] 
set_property PACKAGE_PIN H17 [get_ports {VGA_COLOUR[6]}]                
            set_property IOSTANDARD LVCMOS33 [get_ports {VGA_COLOUR[6]}] 
set_property PACKAGE_PIN G17 [get_ports {VGA_COLOUR[7]}]                
            set_property IOSTANDARD LVCMOS33 [get_ports {VGA_COLOUR[7]}] 
set_property PACKAGE_PIN P19 [get_ports VGA_HS]                        
            set_property IOSTANDARD LVCMOS33 [get_ports VGA_HS]    
set_property PACKAGE_PIN R19 [get_ports VGA_VS]                        
            set_property IOSTANDARD LVCMOS33 [get_ports VGA_VS]   

set_property PACKAGE_PIN V14 [get_ports Interrupt1]                        
            set_property IOSTANDARD LVCMOS33 [get_ports Interrupt1]   

